# Generated by Django 2.2.12 on 2025-06-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='color',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ingroup1_info',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ingroup1_specs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ingroup2_info',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ingroup2_specs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ingroup3_info',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ingroup3_specs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ingroup4_info',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ingroup4_specs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='smiley1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='smiley2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='smiley3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='smiley4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='smiley5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='smiley6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='treatment',
        ),
    ]
