# Generated by Django 2.2.12 on 2025-06-15 11:15

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0002_auto_20250614_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aa_favor1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aa_favor2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aa_favor3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aa_rand',
        ),
        migrations.AddField(
            model_name='player',
            name='aa_belief_disadvantage_disabilities',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that people with disabilities are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_belief_disadvantage_minorities',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that racial minorities are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_belief_disadvantage_women',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that women are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_belief_effort_disabilities',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that people with disabilities are exerting less effort to perform strongly in everyday life (e.g., education or work) than the average member of society?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_belief_effort_minorities',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that racial minorities are exerting less effort to perform strongly in everyday life (e.g., education or work) than the average member of society?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_belief_effort_women',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that women are exerting less effort to perform strongly in everyday life (e.g., education or work) than the average member of society?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_belief_skills_disabilities',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that people with disabilities tend to have lower inborn skills than the average member of society?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_belief_skills_minorities',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that racial minorities tend to have lower inborn skills than the average member of society?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_belief_skills_women',
            field=otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that women tend to have lower inborn skills than the average member of society?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_favor_disabilities',
            field=otree.db.models.StringField(choices=[('Favor', 'Favor'), ('Oppose', 'Oppose'), ('No opinion', 'No opinion')], max_length=10000, null=True, verbose_name='Do you generally favor or oppose affirmative action programs for people with disabilities?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_favor_minorities',
            field=otree.db.models.StringField(choices=[('Favor', 'Favor'), ('Oppose', 'Oppose'), ('No opinion', 'No opinion')], max_length=10000, null=True, verbose_name='Do you generally favor or oppose affirmative action programs for racial minorities?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_favor_women',
            field=otree.db.models.StringField(choices=[('Favor', 'Favor'), ('Oppose', 'Oppose'), ('No opinion', 'No opinion')], max_length=10000, null=True, verbose_name='Do you generally favor or oppose affirmative action programs for women?'),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_rand_order',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
