# Generated by Django 2.2.12 on 2025-06-21 15:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0003_auto_20250615_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='AA_affected',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Do you believe that you have ever been affected by affirmative action in your life?'),
        ),
        migrations.AddField(
            model_name='player',
            name='AA_affected_yes',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='If yes, please state the context/kind of affirmative action measures:'),
        ),
        migrations.AddField(
            model_name='player',
            name='AA_benefited',
            field=otree.db.models.StringField(choices=[('Yes, I believe I have rather benefited', 'Yes, I believe I have rather benefited'), ('No, I believe I have rather been harmed', 'No, I believe I have rather been harmed')], max_length=10000, null=True, verbose_name='Do you believe that you have ever benefited from affirmative action in your life?'),
        ),
        migrations.AddField(
            model_name='player',
            name='AA_context',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please state the context/kind of affirmative action measure(s):'),
        ),
        migrations.AddField(
            model_name='player',
            name='blind',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Are you blind, or do you have serious difficulty seeing, even when wearing glasses?'),
        ),
        migrations.AddField(
            model_name='player',
            name='concentration',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Because of a physical, mental, or emotional condition, do you have serious difficulty concentrating, remembering,or making decisions?'),
        ),
        migrations.AddField(
            model_name='player',
            name='deaf',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Are you deaf, or do you have serious difficulty hearing?'),
        ),
        migrations.AddField(
            model_name='player',
            name='dressing',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Do you have difficulty dressing or bathing?'),
        ),
        migrations.AddField(
            model_name='player',
            name='errands',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name="Because of a physical, mental, or emotional condition, do you have difficulty doing errands alone such asvisiting a doctor's office or shopping?"),
        ),
        migrations.AddField(
            model_name='player',
            name='walking',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Do you have serious difficulty walking or climbing stairs?'),
        ),
    ]
