# Generated by Django 2.2.12 on 2025-06-21 15:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0004_auto_20250621_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='concentration',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Because of a physical, mental, or emotional condition, do you have serious difficulty concentrating, remembering, or making decisions?'),
        ),
    ]
