# Generated by Django 2.2.12 on 2025-06-21 15:21

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0005_auto_20250621_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='errands',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name="Because of a physical, mental, or emotional condition, do you have difficulty doing errands alone such as visiting a doctor's office or shopping?"),
        ),
    ]
