# Generated by Django 2.2.12 on 2025-06-21 15:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0006_auto_20250621_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='AA_affected_yes',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='If yes, please state the context/kind of affirmative action measures:'),
        ),
    ]
