# Generated by Django 2.2.12 on 2025-06-21 16:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0010_auto_20250621_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='efficiency_loss_women',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that affirmative action programs for <strong>women</strong> induce efficiency losses, \n        e.g., due to less productive people being admitted to university or being hired or promoted?'),
        ),
    ]
