# Generated by Django 2.2.12 on 2025-06-21 21:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0012_auto_20250621_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ProlificID',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Please enter your Prolific ID to start the study.'),
        ),
    ]
