# Generated by Django 2.2.12 on 2025-06-21 21:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0013_player_prolificid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='aa_belief_disadvantage_disabilities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that people with disabilities are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_disadvantage_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that racial minorities are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_disadvantage_women',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that women are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_effort_disabilities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that people with disabilities are exerting less effort to perform strongly in everyday life (e.g., education or work) than the average member of society?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_effort_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that racial minorities are exerting less effort to perform strongly in everyday life (e.g., education or work) than the average member of society?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_effort_women',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that women are exerting less effort to perform strongly in everyday life (e.g., education or work) than the average member of society?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_skills_disabilities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that people with disabilities tend to have lower inborn skills than the average member of society?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_skills_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that racial minorities tend to have lower inborn skills than the average member of society?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_skills_women',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To what extent do you believe that women tend to have lower inborn skills than the average member of society?'),
        ),
    ]
