# Generated by Django 2.2.12 on 2025-07-06 09:49

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0014_auto_20250621_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aa_order_disadvantage',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_order_effort',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='aa_order_skills',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
