# Generated by Django 2.2.12 on 2025-07-06 09:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0015_auto_20250706_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aa_order_favor',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
