# Generated by Django 2.2.12 on 2025-07-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0016_player_aa_order_favor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aa_rand_order',
        ),
    ]
