# Generated by Django 2.2.12 on 2025-07-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0017_remove_player_aa_rand_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aa_order_disadvantage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aa_order_effort',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aa_order_favor',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aa_order_skills',
        ),
    ]
