# Generated by Django 2.2.12 on 2025-07-06 10:51

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0020_auto_20250706_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='aa_order_disadvantage',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_order_effort',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_order_skills',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
