# Generated by Django 2.2.12 on 2025-07-10 17:13

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0022_auto_20250706_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='IQ',
            field=otree.db.models.StringField(choices=[('No high school diploma', 'No high school diploma'), ('High school diploma or equivalent', 'High school diploma or equivalent'), ('Some college but no degree', 'Some college but no degree'), ('Associate degree in college (2-year college)', 'Associate degree in college (2-year college)'), ("Bachelor's degree (4-year college)", "Bachelor's degree (4-year college)"), ("Master's degree (For example: MA, MS, MEng, MEd, MSW, MBA)", "Master's degree (For example: MA, MS, MEng, MEd, MSW, MBA)"), ('Professional School Degree or Doctorate Degree (For example: MD, DDS, DVM, LLB, JD, PhD, EdD)', 'Professional School Degree or Doctorate Degree (For example: MD, DDS, DVM, LLB, JD, PhD, EdD)')], max_length=10000, null=True, verbose_name='What is the highest level of school you \n        have completed or the highest degree you have received?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_disadvantage_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that people belonging to racial minorities are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_effort_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that people belonging to racial minorities are exerting less effort to perform strongly in everyday life (e.g. in education or work environments) than people who do not belong to a racial minority?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_skills_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that people belonging to racial minorities tend to have lower inborn skills than people who do not belong to a racial minority?'),
        ),
    ]
