# Generated by Django 2.2.12 on 2025-07-10 17:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0023_auto_20250710_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='aa_order_disadvantage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aa_order_effort',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aa_order_favor',
        ),
        migrations.RemoveField(
            model_name='player',
            name='aa_order_skills',
        ),
        migrations.AddField(
            model_name='player',
            name='aa_order_groups',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
