# Generated by Django 2.2.12 on 2025-07-10 17:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0024_auto_20250710_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='aa_belief_disadvantage_disabilities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that <strong>people with disabilities</strong> are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_disadvantage_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that people belonging to <strong>racial minorities</strong> are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_disadvantage_women',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that <strong>women</strong> are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_effort_disabilities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that <strong>people with disabilities</strong> are exerting less effort to perform strongly in everyday life (e.g. in education or work environments) than people who are not disabled?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_effort_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that people belonging to <strong>racial minorities</strong> are exerting less effort to perform strongly in everyday life (e.g. in education or work environments) than people who do not belong to a racial minority?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_effort_women',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that <strong>women</strong> are exerting less effort to perform strongly in everyday life (e.g. in education or work environments) than men?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_skills_disabilities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that <strong>people with disabilities</strong> tend to have lower inborn skills than people who are not disabled?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_skills_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that people belonging to <strong>racial minorities</strong> tend to have lower inborn skills than people who do not belong to a racial minority?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='aa_belief_skills_women',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that <strong>women</strong> tend to have lower inborn skills than men?'),
        ),
    ]
