# Generated by Django 2.2.12 on 2025-08-15 14:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0027_auto_20250815_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='aa_belief_disadvantage_women',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that <strong>women</strong> are facing unjustified disadvantage and/or discrimination in everyday life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='efficiency_loss_racial_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that affirmative action programs for <strong>racial minorities</strong>\n         induce efficiency losses, e.g., due to less productive people being admitted to university or being hired or \n         promoted?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='efficiency_loss_women',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that affirmative action programs for <strong>women</strong> induce efficiency losses, \n        e.g., due to less productive people being admitted to university or being hired or promoted?'),
        ),
    ]
