# Generated by Django 2.2.12 on 2025-08-15 14:23

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0028_auto_20250815_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='aa_favor_women',
            field=otree.db.models.StringField(choices=[('Favor', 'Favor'), ('Oppose', 'Oppose'), ('No opinion', 'No opinion')], max_length=10000, null=True, verbose_name='Do you generally favor or oppose affirmative action programs for <strong>women</strong>?'),
        ),
    ]
