# Generated by Django 2.2.12 on 2025-08-16 09:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0030_auto_20250815_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='efficiency_loss_racial_minorities',
        ),
        migrations.AddField(
            model_name='player',
            name='efficiency_loss_minorities',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='To which extent do you believe that affirmative action programs for racial minorities\n         induce efficiency losses, e.g., due to less productive people being admitted to university or being hired or \n         promoted?'),
        ),
    ]
