# Generated by Django 2.2.12 on 2025-08-16 10:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('app5_p1112_quest_update', '0031_auto_20250816_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='AA_benefited',
            field=otree.db.models.StringField(blank=True, choices=[('Yes, I believe I have rather benefited', 'Yes, I believe I have rather benefited'), ('No, I believe I have rather been harmed', 'No, I believe I have rather been harmed')], max_length=10000, null=True, verbose_name='Do you believe that you have ever benefited from affirmative action in your life?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='AA_context',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Please state the context/kind of affirmative action measure(s):'),
        ),
    ]
